
[Interface]
Address = 10.101.0.8/32
PrivateKey = QAqdj+l+dO9i6XZwrY36JnfeE8KKYaGleRVXuXjdBW8=
PostUp = printf 'You can now access http://0.0.0.0:5000 on https://u8817z.tunnel.pyjam.as/ ✨\n'

[Peer]
PublicKey = bNRveuBZ7zutCgVqM1EY7aEoRjZYtll3Xd5nVhUbzCk=
AllowedIPs = 10.101.0.1/32
Endpoint = tunnel.pyjam.as:55555
PersistentKeepalive = 21
